server:
  port: 8765
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        predicates:
          - name: Path
            args:
              pattern: /${servicename}/**
        filters:
          - name: RewritePath
            args:
              regexp: /${servicename}/(?<remaining>.*)
              replacement: /$\{remaining}
#      routes:
#      - id: cambio-service
#        uri: lb://cambio-service
#        predicates:
#        - Path=/cambio-service/**
#      - id: book-service
#        uri: lb://book-service
#        predicates:
#        - Path=/book-service/**